// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2FjMTQe6KmCtOI47qBpo1ew-on5Bd8mg',
    appId: '1:922067495219:web:344958510ddfadb0bdb646',
    messagingSenderId: '922067495219',
    projectId: 'ms-app-9754d',
    authDomain: 'ms-app-9754d.firebaseapp.com',
    storageBucket: 'ms-app-9754d.firebasestorage.app',
    measurementId: 'G-NBJBDBLD0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv-vOgyPBSWKm9ey3PcCszrxxOtOwvgBA',
    appId: '1:922067495219:android:13c620fc3f42cbe8bdb646',
    messagingSenderId: '922067495219',
    projectId: 'ms-app-9754d',
    storageBucket: 'ms-app-9754d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqVd_VkA4JhkeLii67TKugQgbvOXdxQCo',
    appId: '1:922067495219:ios:b184ce2277e57553bdb646',
    messagingSenderId: '922067495219',
    projectId: 'ms-app-9754d',
    storageBucket: 'ms-app-9754d.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqVd_VkA4JhkeLii67TKugQgbvOXdxQCo',
    appId: '1:922067495219:ios:b184ce2277e57553bdb646',
    messagingSenderId: '922067495219',
    projectId: 'ms-app-9754d',
    storageBucket: 'ms-app-9754d.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2FjMTQe6KmCtOI47qBpo1ew-on5Bd8mg',
    appId: '1:922067495219:web:55959ddf83bb9d95bdb646',
    messagingSenderId: '922067495219',
    projectId: 'ms-app-9754d',
    authDomain: 'ms-app-9754d.firebaseapp.com',
    storageBucket: 'ms-app-9754d.firebasestorage.app',
    measurementId: 'G-L6BS3CB6D5',
  );
}
